Add read methods for use with access to a JsonElement
jglrxavpok/Hephaistos pull request #20
Opened 2022-04-13 20:26 UTC by outroddet

For deserializing directly from a JsonElement to NBT

2022-04-16 21:15 UTC, jglrxavpok requested changes
Apologies for the late answer, I completly missed the email notification.
There needs to be a few changes, but I agree with the intent.

2022-04-16 21:15 UTC, jglrxavpok commented on build.gradle.kts
> +    version = "2.4.3"
Don't update the version directly in PRs.

2022-04-16 21:15 UTC, jglrxavpok commented on gson/src/main/kotlin/org/jglrxavpok/hephaistos/json/NBTGsonReader.kt
> +
Why the empty space?

2022-04-16 21:15 UTC, jglrxavpok commented on gson/src/main/kotlin/org/jglrxavpok/hephaistos/json/NBTGsonReader.kt
> +class NBTGsonReader(private val reader: Reader = Reader.nullReader()): AutoCloseable, Closeable {
I would prefer the methods to be static/companion-object-methods rather than exposing a way to read without a proper reader. Make the parse method a companion method if necessary.

2022-04-17 07:07 UTC, outroddet commented
Hey, thx for your answer. I changed

2022-04-17 11:27 UTC, jglrxavpok commented
Would be perfect if you could add a few tests inside common/src/test. Also, is there a reason why your parseWithGuess method is not longer here?

2022-04-22 19:05 UTC, outroddet commented
When I add test to "common" there is a circular dependency between common and gson.

2022-04-30 08:58 UTC, jglrxavpok commented
My bad, the tests should be inside gson/test.
As for parseWithGuess, I guess I misremembered something, forget it.

2022-05-10 08:25 UTC, outroddet commented
I added some tests. Hopefully it's fine now.

2022-05-14 12:44 UTC, merged