Greatly improved palette & NBT speeds
jglrxavpok/Hephaistos pull request #32
Opened 2022-09-06 09:50 UTC by KodingDev

# Overview

When working with Minestom on a Schematic -> Slime World converter, I noticed a few potential performance issues when profiling the app. We use both this library & Minestom extensively for a project, and in the process were able to nearly:

* Over 2x the speed of the `ChunkColumn.set` method
* Greatly decrease the overhead of the `Palette` class, helping with achieving the above result
* Increase IO throughput of array types in NBT encoding/decoding
* And further.

# Quick Note

The main thing to note is that this includes the [fastutil](https://github.com/vigna/fastutil) library, which is quite bulky. We don't use a lot of their classes as they are extremely specific, so projects depending on future versions - noting Minestom here - may wish to recommend exclusion of classes from the JAR which are unused here.

# Profiler screenshots

Performance testing was done by profiling the `test` Gradle task as it was running, to get a wholistic view of how influential each change was. The screenshots are in descending order.

### Original

![image](https://user-images.githubusercontent.com/23714764/188603807-9b288858-2b58-4892-8932-4bbea309ba08.png)

### Final

![image](https://user-images.githubusercontent.com/23714764/188604326-aad9d808-98f9-4c85-bf79-4dd7471f237d.png)

<details>
<summary>Intermediary Screenshots</summary>

### Intermediary 1

![image](https://user-images.githubusercontent.com/23714764/188604109-75a26739-f66f-4a49-b7b2-6302a15ac9ad.png)

### Intermediary 2

![image](https://user-images.githubusercontent.com/23714764/188604170-e60647a2-4200-4631-9d3b-d1b4466d4047.png)

### Intermediary 3

![image](https://user-images.githubusercontent.com/23714764/188604189-8efce092-993a-447e-83bc-87f7ce3901b5.png)

### Intermediary 4

![image](https://user-images.githubusercontent.com/23714764/188604208-c1038ee1-050c-4488-9ba3-e52c14019220.png)

### Intermediary 5

![image](https://user-images.githubusercontent.com/23714764/188604242-6b7ec215-9e81-4171-ab68-26eb9c595d3a.png)

### Intermediary 6

![image](https://user-images.githubusercontent.com/23714764/188604286-23615ae1-4b35-4e93-b910-59c315fc85ae.png)

</details>

2022-09-06 10:35 UTC, KodingDev commented
Here's another comparison when loading an anvil world using Minestom's anvil loader, without doing anything outside of upgrading the dependency.

### Before

![image](https://user-images.githubusercontent.com/23714764/188613947-5fc17ef4-fab2-4a04-9a65-3775bb343ebe.png)

### After

![image](https://user-images.githubusercontent.com/23714764/188614013-efc02a22-321a-4ec5-ad1d-7308dee36c15.png)

2022-09-06 17:05 UTC, jglrxavpok requested changes
The benchmarks look impressive, but I disagree on a few choices in this PR.
I also think there is a tiny bit more that can be done for performance (see comments).

Other than, after addressing my various comments, I think it will be good for merging.

2022-09-06 17:05 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +            val value = ImmutableIntArray(*outArray)
Are you sure the byte order is always correct?

I understand the idea, I like the idea, but I wonder if there is a better way to do this, with fewer allocations. Maybe there is none, but I'll think about it.

2022-09-06 17:05 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTLongArray.kt
>      }
Same than ImmutableIntArray

2022-09-06 17:05 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTLongArray.kt
>              return NBTLongArray(value)
Same than ImmutableIntArray

2022-09-06 17:05 UTC, jglrxavpok commented on common/build.gradle.kts
> +    implementation("it.unimi.dsi:fastutil:8.5.8")
I am not a fan of adding dependencies if we can avoid them, but here the specialized maps look very interesting, so maybe that's fine.
Do you have a comparison without using fastutil (but keeping everything else in this PR the same) ?

2022-09-06 23:06 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +            referenceCounts[block] = 1
It needs to be added to the map in order to be incremented, when the result is 0 we can assume it's not in the map and so we need to add it since it's not done automatically.

2022-09-06 23:10 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/ChunkSection.kt
> +        if(!Options.BreakPalettesForPerformance.active) {
It's off by default. Since the only method of removing this check is to explicitly enable it, would it not be assumed that the user knows what they're doing if they're going out of their way to enable it?

2022-09-06 23:17 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/Options.kt
> +    BreakPalettesForPerformance(false)
Disabled by default, the functionality is the same by default. The user needs to explicitly disable those checks.

2022-09-06 23:18 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +        }
If the element is in the map then it's implicitly > 0. I also believe that function is faster compared to retrieving the value as well but I could be wrong (?)

2022-09-06 23:24 UTC, KodingDev commented on common/build.gradle.kts
> +    implementation("it.unimi.dsi:fastutil:8.5.8")
You can compare between the intermediary 1 and 2, specifically the `increaseReferences` method. I changed it from using a `HashSet` to the fastutil equivalent, the result can be seen below.

<img width="261" alt="CleanShot 2022-09-07 at 09 24 16@2x" src="https://user-images.githubusercontent.com/23714764/188757090-7ae77684-0bb0-41dd-9937-a45957245c79.png">
<img width="247" alt="CleanShot 2022-09-07 at 09 24 22@2x" src="https://user-images.githubusercontent.com/23714764/188757102-522cfa52-ceee-45d8-8163-25791e8eac6b.png">

2022-09-06 23:27 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +    internal val referenceCounts = Object2IntOpenHashMap<ElementType>()
Used in this function which is in the `ChunkSection` class.
<img width="475" alt="CleanShot 2022-09-07 at 09 26 38@2x" src="https://user-images.githubusercontent.com/23714764/188757335-9dbd809a-7e2c-49d6-a521-5943f707b518.png">

2022-09-06 23:31 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +        if(!Options.BreakPalettesForPerformance.active) {
It's used in decoding from NBT so I'll keep the check for consistency's sake. See above comment for info on the options.

2022-09-06 23:38 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +        destination.write(buffer.array())
The write function doesn't let us write int arrays, long arrays, etc so we need to allocate the buffer. Removed the for loop in favour of exposing the backing array in a single put call however.

2022-09-06 23:40 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +            val value = ImmutableIntArray(*outArray)
Adjusted a little bit, let me know if this looks better to you. Byte order should be correct.

2022-09-07 16:22 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +    internal val referenceCounts = Object2IntOpenHashMap<ElementType>()
Ok

2022-09-07 16:29 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/ChunkSection.kt
> +        if(!Options.BreakPalettesForPerformance.active) {
Correctness is important, even if it costs a bit of performance. It helps developping against Hephaistos because you can rely on it to tell you if you are doing something wrong.
Also, as soon as you leave the options, users will want to activate it. And then I'll get cryptic issues with `IndexOutOfBoundsException`s because they turned the check off but don't know why it crashes.

2022-09-07 16:30 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +        if(!Options.BreakPalettesForPerformance.active) {
Keeping it as an option -> no, see my other answer.
It might be used when decoding from NBT, but maybe the Palette itself is in a state which does not require the check. I'll check when I find some time.

2022-09-07 16:31 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/Options.kt
> +    BreakPalettesForPerformance(false)
See my other comments.

2022-09-07 16:43 UTC, jglrxavpok requested changes

2022-09-07 16:43 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/ChunkSection.kt
> +            palette.referenceCounts[BlockState.AIR] = 4096
Missed it in the first review, but replace 4096 with a constant, for readability. Could be `EmptyBlockStates.size`.

2022-09-07 16:43 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/ChunkSection.kt
> +        if (empty || blockStates.contentEquals(EmptyBlockStates)) {
Do you often have blockStates == EmptyBlockStates?
How does performance compare between having this check for all palettes, and removing this check and using the 'else' branch for this case (blockStates == EmptyBlockStates) ?

2022-09-07 16:43 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +            referenceCounts[block] = 1
From the fastutil doc:
> Adds an increment to value currently associated with a key.

> Note that this method respects the [default return value](https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/objects/AbstractObject2IntFunction.html#defaultReturnValue()) semantics: when called with a key that does not currently appears in the map, the key will be associated with the default return value plus the given increment.

I think the association can be removed (but at this point it might just be nitpicking)

2022-09-07 16:43 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +        }
Same thing than in `Palette#increaseReference`, we can rely on the addTo to do things for us (but here it is not nitpicking, we can remove the check).
As I said previously, I don't want the flag for breaking correctness, so we will probably keep the table lookup in all cases, so we might as well do it only once.

2022-09-07 16:43 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +        destination.write(buffer.array())
That will work, but I would like to see a memory & CPU comparison for this method (we can assume the behaviour will be the same in NBTLongArray so no need to do it twice) before and after this PR when saving worlds.
Just to see if the allocation is worth it, and making sure @TheMode doesn't panic if memory usage increases.

2022-09-07 16:43 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +            val value = ImmutableIntArray(*outArray)
Same comment than for writeContents.
I want to insist that I think you have a good idea, and that performance should be better with this method.

2022-09-08 14:00 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +            val value = ImmutableIntArray(*outArray)
Not entirely sure what a good approach for this is, worse case scenario we can revert it back to what it was before. Need to think about it more.

2022-09-08 16:26 UTC, jglrxavpok requested changes

2022-09-08 16:26 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/BlockState.kt
> +    var hashCode = 0
Make it private but other than that, I agree with the agree.

2022-09-08 16:26 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/ChunkSection.kt
> +    private fun initializePalette(palette: BlockPalette, isAir: Boolean = false) {
It's private and has only two calls, no need for a default value

2022-09-08 16:26 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/mca/Palette.kt
> +        val visited = mutableSetOf<ElementType>()
Maybe I am blind, but is this set ever updated?

2022-09-08 16:26 UTC, jglrxavpok commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +        }
What is the reasoning behind splitting the writing into small 4ko chunks for large arrays?

Just thought of something: maybe a thread-local static ByteBuffer of some size could be reused for small arrays.

2022-09-09 00:29 UTC, KodingDev commented on common/src/main/kotlin/org/jglrxavpok/hephaistos/nbt/NBTIntArray.kt
> +        }
Reverted writing, improved reading by not allocating anything. Check that over rq

2022-09-15 03:57 UTC, KodingDev commented
Bump on this :)

2022-10-01 19:42 UTC, jglrxavpok approved these changes
I have been able to confirm the performance gains on my end.
I can confirm the CPU & (surprisingly) memory optimizations.

Again, I apologize for the late answer.

2022-10-01 19:42 UTC, jglrxavpok commented on convention-plugins/src/main/kotlin/convention.publication.gradle.kts
> +    }
Remove this and the PR is ready for merging.

2022-10-02 02:27 UTC, KodingDev commented
Signing separated into #33

2022-10-02 08:33 UTC, jglrxavpok approved these changes

2022-10-02 08:34 UTC, merged